version: "3.7"

services:
    database: 
        image: postgres:15-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=prime

volumes:
    postgres_data: